#!/usr/bin/env python3
"""Generate a small 1-bit C bitmap font for BRICK firmware.

The output is deliberately independent of LVGL: glyphs are packed row-major,
one bit per pixel, and can be rendered by any BRICK display adapter.
Requires Pillow (``python -m pip install pillow``).
"""
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def render(font: ImageFont.FreeTypeFont, char: str):
    left, top, right, bottom = font.getbbox(char)
    width = max(1, right - left)
    height = max(1, bottom - top)
    image = Image.new("1", (width, height), 0)
    ImageDraw.Draw(image).text((-left, -top), char, font=font, fill=1)
    rows = []
    stride = (width + 7) // 8
    for y in range(height):
        row = [0] * stride
        for x in range(width):
            if image.getpixel((x, y)):
                row[x // 8] |= 0x80 >> (x & 7)
        rows.append(row)
    return width, height, rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--name", default="brick_bitmap_font")
    parser.add_argument("--size", required=True, type=int)
    parser.add_argument("--chars", default=" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~")
    args = parser.parse_args()

    font = ImageFont.truetype(str(args.font), args.size)
    glyphs = [render(font, char) for char in args.chars]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    out = [
        "// Generated by tools/assets/generate_bitmap_font.py; do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#ifndef BRICK_BITMAP_GLYPH_DEFINED",
        "#define BRICK_BITMAP_GLYPH_DEFINED",
        "struct BrickBitmapGlyph { uint16_t width; uint16_t height; uint16_t stride; const uint8_t* data; };",
        "#endif",
        f"static const uint8_t {args.name}_data[] = {{",
    ]
    offsets = []
    data = []
    for width, height, rows in glyphs:
        stride = (width + 7) // 8
        offsets.append((width, height, stride, len(data)))
        for row in rows:
            data.extend(row)
    for index in range(0, len(data), 16):
        out.append("  " + ", ".join(f"0x{byte:02X}" for byte in data[index:index + 16]) + ",")
    out += ["};", "", f"static const BrickBitmapGlyph {args.name}_glyphs[] = {{"]
    for width, height, stride, offset in offsets:
        out.append(f"  {{{width}, {height}, {stride}, {args.name}_data + {offset}}},")
    out += ["};", f"static const char {args.name}_chars[] = "]
    escaped = "".join("\\x%02X" % ord(char) if ord(char) < 32 or ord(char) > 126 else ("\\\\" if char == "\\" else '\\"' if char == '"' else char) for char in args.chars)
    out[-1] += f'"{escaped}";'
    out += [f"static const uint16_t {args.name}_count = {len(args.chars)};"]
    args.output.write_text("\n".join(out) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
